version: "3.7"

services:
  postgres:
    image: 'bitnami/postgresql:15'
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgresql_data:/bitnami/postgresql
    networks:
      - gateway_ingress

networks:
  gateway_ingress:
    external: true
