version: '3.7'

services:
  redis:
    image: bitnami/redis:7.0
    container_name: redis
    env_file:
      - .env
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - './redis_data:/bitnami/redis/data'
    networks:
      - gateway_ingress

networks:
  gateway_ingress:
    external: true
